In [2]:
import pandas as pd
import glob
import os

folder = "../data/raw/Output_CSV"

files = glob.glob(os.path.join(folder, "*.csv"))

print(files)

dfs = {}

for file in files:
    name = os.path.basename(file).replace(".csv","")
    dfs[name] = pd.read_csv(file)

print(dfs.keys())

['../data/raw/Output_CSV\\acceleration.csv', '../data/raw/Output_CSV\\basal.csv', '../data/raw/Output_CSV\\basis_gsr.csv', '../data/raw/Output_CSV\\basis_skin_temperature.csv', '../data/raw/Output_CSV\\basis_sleep.csv', '../data/raw/Output_CSV\\bolus.csv', '../data/raw/Output_CSV\\exercise.csv', '../data/raw/Output_CSV\\finger_stick.csv', '../data/raw/Output_CSV\\glucose_level.csv', '../data/raw/Output_CSV\\hypo_event.csv', '../data/raw/Output_CSV\\illness.csv', '../data/raw/Output_CSV\\meal.csv', '../data/raw/Output_CSV\\sleep.csv', '../data/raw/Output_CSV\\stressors.csv', '../data/raw/Output_CSV\\temp_basal.csv', '../data/raw/Output_CSV\\work.csv']
dict_keys(['acceleration', 'basal', 'basis_gsr', 'basis_skin_temperature', 'basis_sleep', 'bolus', 'exercise', 'finger_stick', 'glucose_level', 'hypo_event', 'illness', 'meal', 'sleep', 'stressors', 'temp_basal', 'work'])

In [7]:
for name, df in dfs.items():
    print("="*60)
    print(name.upper())
    print("="*60)

    print("shape:", df.shape)
    print("\ncolumns:", df.columns.tolist())

    print("\n Data Type")
    print(df.dtypes)

    print("\nFirst 5 Rows")
    display(df.head())

============================================================
ACCELERATION
============================================================
shape: (228027, 4)

columns: ['Patient', 'Section', 'ts', 'value']

 Data Type
Patient     object
Section     object
ts          object
value      float64
dtype: object

First 5 Rows

           Patient       Section                   ts     value
0  596-ws-training  acceleration  07-04-2027 18:40:00  0.930137
1  596-ws-training  acceleration  07-04-2027 18:41:00  0.929822
2  596-ws-training  acceleration  07-04-2027 18:42:00  0.930140
3  596-ws-training  acceleration  07-04-2027 18:43:00  0.930053
4  596-ws-training  acceleration  07-04-2027 18:44:00  0.930310

============================================================
BASAL
============================================================
shape: (357, 4)

columns: ['Patient', 'Section', 'ts', 'value']

 Data Type
Patient     object
Section     object
ts          object
value      float64
dtype: object

First 5 Rows

           Patient Section                   ts  value
0  596-ws-training   basal  07-04-2027 09:17:23   0.60
1  596-ws-training   basal  07-04-2027 22:00:00   0.45
2  596-ws-training   basal  08-04-2027 00:00:00   0.40
3  596-ws-training   basal  08-04-2027 04:00:00   0.60
4  596-ws-training   basal  08-04-2027 22:00:00   0.45

============================================================
BASIS_GSR
============================================================
shape: (228025, 4)

columns: ['Patient', 'Section', 'ts', 'value']

 Data Type
Patient     object
Section     object
ts          object
value      float64
dtype: object

First 5 Rows

           Patient    Section                   ts     value
0  596-ws-training  basis_gsr  07-04-2027 18:40:00  0.014233
1  596-ws-training  basis_gsr  07-04-2027 18:41:00  0.013551
2  596-ws-training  basis_gsr  07-04-2027 18:42:00  0.013851
3  596-ws-training  basis_gsr  07-04-2027 18:43:00  0.013797
4  596-ws-training  basis_gsr  07-04-2027 18:44:00  0.013761

============================================================
BASIS_SKIN_TEMPERATURE
============================================================
shape: (228021, 4)

columns: ['Patient', 'Section', 'ts', 'value']

 Data Type
Patient     object
Section     object
ts          object
value      float64
dtype: object

First 5 Rows

           Patient                 Section                   ts  value
0  596-ws-training  basis_skin_temperature  07-04-2027 18:40:00  86.91
1  596-ws-training  basis_skin_temperature  07-04-2027 18:41:00  86.86
2  596-ws-training  basis_skin_temperature  07-04-2027 18:42:00  86.80
3  596-ws-training  basis_skin_temperature  07-04-2027 18:43:00  86.74
4  596-ws-training  basis_skin_temperature  07-04-2027 18:44:00  86.68

============================================================
BASIS_SLEEP
============================================================
shape: (199, 6)

columns: ['Patient', 'Section', 'tbegin', 'tend', 'quality', 'type']

 Data Type
Patient    object
Section    object
tbegin     object
tend       object
quality     int64
type       object
dtype: object

First 5 Rows

,Patient,Section,tbegin,tend,quality,type
0,596-ws-training,basis_sleep,07-04-2027 18:40:00,07-04-2027 19:32:00,0,
1,596-ws-training,basis_sleep,07-04-2027 22:58:00,08-04-2027 07:27:00,0,
2,596-ws-training,basis_sleep,08-04-2027 17:53:00,08-04-2027 18:47:00,0,
3,596-ws-training,basis_sleep,08-04-2027 23:06:00,09-04-2027 05:01:00,0,
4,596-ws-training,basis_sleep,11-04-2027 23:40:00,12-04-2027 06:20:00,0,

============================================================
BOLUS
============================================================
shape: (1568, 6)

columns: ['Patient', 'Section', 'ts_begin', 'ts_end', 'type', 'dose']

 Data Type
Patient      object
Section      object
ts_begin     object
ts_end       object
type         object
dose        float64
dtype: object

First 5 Rows

,Patient,Section,ts_begin,ts_end,type,dose
0,596-ws-training,bolus,07-04-2027 12:05:42,07-04-2027 12:05:42,normal,3.4
1,596-ws-training,bolus,07-04-2027 13:21:05,07-04-2027 13:21:05,normal,2.0
2,596-ws-training,bolus,07-04-2027 17:29:59,07-04-2027 17:29:59,normal,5.0
3,596-ws-training,bolus,08-04-2027 07:30:58,08-04-2027 07:30:58,normal,1.5
4,596-ws-training,bolus,08-04-2027 08:19:52,08-04-2027 08:19:52,normal,3.3

============================================================
EXERCISE
============================================================
shape: (61, 7)

columns: ['Patient', 'Section', 'ts', 'intensity', 'type', 'duration', 'competitive']

 Data Type
Patient         object
Section         object
ts              object
intensity        int64
type            object
duration         int64
competitive    float64
dtype: object

First 5 Rows

,Patient,Section,ts,intensity,type,duration,competitive
0,596-ws-training,exercise,07-04-2027 13:25:00,5,,117,NaN
1,596-ws-training,exercise,07-04-2027 15:43:00,5,,0,NaN
2,596-ws-training,exercise,08-04-2027 09:13:00,3,,39,NaN
3,596-ws-training,exercise,09-04-2027 09:03:00,3,,178,NaN
4,596-ws-training,exercise,11-04-2027 07:45:00,6,,45,NaN

============================================================
FINGER_STICK
============================================================
shape: (1691, 4)

columns: ['Patient', 'Section', 'ts', 'value']

 Data Type
Patient    object
Section    object
ts         object
value       int64
dtype: object

First 5 Rows

           Patient       Section                   ts  value
0  596-ws-training  finger_stick  07-04-2027 11:56:14     75
1  596-ws-training  finger_stick  07-04-2027 13:19:33    200
2  596-ws-training  finger_stick  07-04-2027 18:09:07    103
3  596-ws-training  finger_stick  07-04-2027 22:19:09    128
4  596-ws-training  finger_stick  08-04-2027 04:37:12    132

============================================================
GLUCOSE_LEVEL
============================================================
shape: (65535, 4)

columns: ['Patient', 'Section', 'ts', 'value']

 Data Type
Patient    object
Section    object
ts         object
value       int64
dtype: object

First 5 Rows

           Patient        Section                   ts  value
0  596-ws-training  glucose_level  09-04-2027 16:15:00    142
1  596-ws-training  glucose_level  09-04-2027 16:20:00    142
2  596-ws-training  glucose_level  09-04-2027 16:25:00    142
3  596-ws-training  glucose_level  09-04-2027 16:30:00    141
4  596-ws-training  glucose_level  09-04-2027 16:35:00    139

============================================================
HYPO_EVENT
============================================================
shape: (45, 3)

columns: ['Patient', 'Section', 'ts']

 Data Type
Patient    object
Section    object
ts         object
dtype: object

First 5 Rows

           Patient     Section                   ts
0  596-ws-training  hypo_event  07-04-2027 12:17:00
1  596-ws-training  hypo_event  07-04-2027 16:25:00
2  596-ws-training  hypo_event  23-04-2027 15:39:00
3  596-ws-training  hypo_event  23-04-2027 16:15:00
4  596-ws-training  hypo_event  24-04-2027 15:10:00

============================================================
ILLNESS
============================================================
shape: (3, 6)

columns: ['Patient', 'Section', 'ts_begin', 'ts_end', 'type', 'description']

 Data Type
Patient         object
Section         object
ts_begin        object
ts_end         float64
type           float64
description     object
dtype: object

First 5 Rows

           Patient  Section             ts_begin  ts_end  type description
0  596-ws-training  illness  12-05-2027 03:25:00     NaN   NaN
1  567-ws-training  illness  18-01-2027 12:26:00     NaN   NaN
2  552-ws-training  illness  16-04-2025 20:11:00     NaN   NaN

============================================================
MEAL
============================================================
shape: (702, 5)

columns: ['Patient', 'Section', 'ts', 'type', 'carbs']

 Data Type
Patient    object
Section    object
ts         object
type       object
carbs       int64
dtype: object

First 5 Rows

           Patient Section                   ts            type  carbs
0  596-ws-training    meal  07-04-2027 12:08:00           Lunch     39
1  596-ws-training    meal  07-04-2027 12:17:00  HypoCorrection     20
2  596-ws-training    meal  07-04-2027 16:25:00  HypoCorrection     32
3  596-ws-training    meal  07-04-2027 17:19:00          Dinner     50
4  596-ws-training    meal  07-04-2027 19:39:00           Snack      5

============================================================
SLEEP
============================================================
shape: (150, 5)

columns: ['Patient', 'Section', 'ts_begin', 'ts_end', 'quality']

 Data Type
Patient     object
Section     object
ts_begin    object
ts_end      object
quality      int64
dtype: object

First 5 Rows

           Patient Section             ts_begin               ts_end  quality
0  596-ws-training   sleep  08-04-2027 07:10:00  07-04-2027 22:54:00        2
1  596-ws-training   sleep  09-04-2027 05:57:00  08-04-2027 22:22:00        3
2  596-ws-training   sleep  10-04-2027 04:20:00  09-04-2027 23:02:00        2
3  596-ws-training   sleep  11-04-2027 06:24:00  10-04-2027 22:27:00        2
4  596-ws-training   sleep  12-04-2027 06:30:00  11-04-2027 23:29:00        3

============================================================
STRESSORS
============================================================
shape: (2, 5)

columns: ['Patient', 'Section', 'ts', 'type', 'description']

 Data Type
Patient        object
Section        object
ts             object
type           object
description    object
dtype: object

First 5 Rows

           Patient    Section                   ts type description
0  596-ws-training  stressors  13-04-2027 15:14:00
1  544-ws-training  stressors  18-05-2027 14:14:00

============================================================
TEMP_BASAL
============================================================
shape: (355, 5)

columns: ['Patient', 'Section', 'ts_begin', 'ts_end', 'value']

 Data Type
Patient      object
Section      object
ts_begin     object
ts_end       object
value       float64
dtype: object

First 5 Rows

,Patient,Section,ts_begin,ts_end,value
0,596-ws-training,temp_basal,01-05-2027 08:22:50,01-05-2027 10:52:50,0.30
1,596-ws-training,temp_basal,06-05-2027 10:50:07,06-05-2027 12:50:07,0.25
2,596-ws-training,temp_basal,07-05-2027 11:08:19,07-05-2027 13:08:19,0.30
3,596-ws-training,temp_basal,08-05-2027 09:53:55,08-05-2027 13:53:55,0.20
4,596-ws-training,temp_basal,14-05-2027 08:15:05,14-05-2027 11:15:05,0.20

============================================================
WORK
============================================================
shape: (52, 5)

columns: ['Patient', 'Section', 'ts_begin', 'ts_end', 'intensity']

 Data Type
Patient      object
Section      object
ts_begin     object
ts_end       object
intensity     int64
dtype: object

First 5 Rows

,Patient,Section,ts_begin,ts_end,intensity
0,552-ws-training,work,23-04-2025 06:15:00,23-04-2025 16:00:00,3
1,552-ws-training,work,24-04-2025 05:45:00,24-04-2025 15:36:00,2
2,552-ws-training,work,29-04-2025 06:50:00,29-04-2025 16:30:00,2
3,552-ws-training,work,30-04-2025 05:45:00,30-04-2025 15:30:00,2
4,552-ws-training,work,13-05-2025 07:15:00,13-05-2025 15:40:00,2

In [9]:
missing = {}

for name, df in dfs.items():
    missing[name] = df.isnull().sum()

for name, values in missing.items():
    print('\n',name)
    print(values)

 acceleration
Patient    0
Section    0
ts         0
value      0
dtype: int64

 basal
Patient    0
Section    0
ts         0
value      0
dtype: int64

 basis_gsr
Patient    0
Section    0
ts         0
value      0
dtype: int64

 basis_skin_temperature
Patient    0
Section    0
ts         0
value      0
dtype: int64

 basis_sleep
Patient    0
Section    0
tbegin     0
tend       0
quality    0
type       0
dtype: int64

 bolus
Patient     0
Section     0
ts_begin    0
ts_end      0
type        0
dose        0
dtype: int64

 exercise
Patient         0
Section         0
ts              0
intensity       0
type            0
duration        0
competitive    61
dtype: int64

 finger_stick
Patient    0
Section    0
ts         0
value      0
dtype: int64

 glucose_level
Patient    0
Section    0
ts         0
value      0
dtype: int64

 hypo_event
Patient    0
Section    0
ts         0
dtype: int64

 illness
Patient        0
Section        0
ts_begin       0
ts_end         3
type           3
description    0
dtype: int64

 meal
Patient    0
Section    0
ts         0
type       0
carbs      0
dtype: int64

 sleep
Patient     0
Section     0
ts_begin    0
ts_end      0
quality     0
dtype: int64

 stressors
Patient        0
Section        0
ts             0
type           0
description    0
dtype: int64

 temp_basal
Patient     0
Section     0
ts_begin    0
ts_end      0
value       0
dtype: int64

 work
Patient      0
Section      0
ts_begin     0
ts_end       0
intensity    0
dtype: int64

In [10]:
for name, df in dfs.items():
    print(name, ':', df.duplicated().sum())

acceleration : 0
basal : 0
basis_gsr : 0
basis_skin_temperature : 0
basis_sleep : 0
bolus : 0
exercise : 0
finger_stick : 0
glucose_level : 0
hypo_event : 0
illness : 0
meal : 0
sleep : 0
stressors : 0
temp_basal : 0
work : 0

In [11]:
for name, df in dfs.items():
    print('='*60)
    print(name)
    print('='*60)

    print(df.describe(include='all'))

============================================================
acceleration
============================================================
                Patient       Section                   ts          value
count            228027        228027               228027  228027.000000
unique                6             1               194951            NaN
top     544-ws-training  acceleration  22-05-2027 20:34:00            NaN
freq              53219        228027                    3            NaN
mean                NaN           NaN                  NaN       1.176843
std                 NaN           NaN                  NaN       1.609444
min                 NaN           NaN                  NaN       0.000000
25%                 NaN           NaN                  NaN       0.964664
50%                 NaN           NaN                  NaN       1.012496
75%                 NaN           NaN                  NaN       1.045926
max                 NaN           NaN                  NaN      16.064701
============================================================
basal
============================================================
                Patient Section                   ts       value
count               357     357                  357  357.000000
unique                6       1                  348         NaN
top     567-ws-training   basal  26-05-2027 00:00:00         NaN
freq                135     357                    3         NaN
mean                NaN     NaN                  NaN    1.249720
std                 NaN     NaN                  NaN    0.376112
min                 NaN     NaN                  NaN    0.400000
25%                 NaN     NaN                  NaN    1.000000
50%                 NaN     NaN                  NaN    1.200000
75%                 NaN     NaN                  NaN    1.500000
max                 NaN     NaN                  NaN    2.000000
============================================================
basis_gsr
============================================================
                Patient    Section                   ts          value
count            228025     228025               228025  228025.000000
unique                6          1               194949            NaN
top     544-ws-training  basis_gsr  22-05-2027 20:33:00            NaN
freq              53219     228025                    3            NaN
mean                NaN        NaN                  NaN       1.165320
std                 NaN        NaN                  NaN       4.168674
min                 NaN        NaN                  NaN       0.000000
25%                 NaN        NaN                  NaN       0.036669
50%                 NaN        NaN                  NaN       0.137852
75%                 NaN        NaN                  NaN       0.594562
max                 NaN        NaN                  NaN      75.074359
============================================================
basis_skin_temperature
============================================================
                Patient                 Section                   ts  \
count            228021                  228021               228021
unique                6                       1               194947
top     544-ws-training  basis_skin_temperature  22-05-2027 20:30:00
freq              53219                  228021                    3
mean                NaN                     NaN                  NaN
std                 NaN                     NaN                  NaN
min                 NaN                     NaN                  NaN
25%                 NaN                     NaN                  NaN
50%                 NaN                     NaN                  NaN
75%                 NaN                     NaN                  NaN
max                 NaN                     NaN                  NaN

                value
count   228021.000000
unique            NaN
top               NaN
freq              NaN
mean        86.332590
std          7.118175
min          0.000000
25%         84.670000
50%         87.130000
75%         89.150000
max         96.570000
============================================================
basis_sleep
============================================================
                Patient      Section               tbegin  \
count               199          199                  199
unique                6            1                  199
top     544-ws-training  basis_sleep  07-04-2027 18:40:00
freq                 52          199                    1
mean                NaN          NaN                  NaN
std                 NaN          NaN                  NaN
min                 NaN          NaN                  NaN
25%                 NaN          NaN                  NaN
50%                 NaN          NaN                  NaN
75%                 NaN          NaN                  NaN
max                 NaN          NaN                  NaN

                       tend  quality type
count                   199    199.0  199
unique                  199      NaN    1
top     07-04-2027 19:32:00      NaN
freq                      1      NaN  199
mean                    NaN      0.0  NaN
std                     NaN      0.0  NaN
min                     NaN      0.0  NaN
25%                     NaN      0.0  NaN
50%                     NaN      0.0  NaN
75%                     NaN      0.0  NaN
max                     NaN      0.0  NaN
============================================================
bolus
============================================================
                Patient Section             ts_begin               ts_end  \
count              1568    1568                 1568                 1568
unique                6       1                 1568                 1568
top     552-ws-training   bolus  07-04-2027 12:05:42  07-04-2027 12:05:42
freq                336    1568                    1                    1
mean                NaN     NaN                  NaN                  NaN
std                 NaN     NaN                  NaN                  NaN
min                 NaN     NaN                  NaN                  NaN
25%                 NaN     NaN                  NaN                  NaN
50%                 NaN     NaN                  NaN                  NaN
75%                 NaN     NaN                  NaN                  NaN
max                 NaN     NaN                  NaN                  NaN

          type         dose
count     1568  1568.000000
unique       4          NaN
top     normal          NaN
freq      1515          NaN
mean       NaN     6.423023
std        NaN     5.047204
min        NaN     0.100000
25%        NaN     2.500000
50%        NaN     5.000000
75%        NaN     9.200000
max        NaN    25.000000
============================================================
exercise
============================================================
                Patient   Section                   ts  intensity type  \
count                61        61                   61  61.000000   61
unique                4         1                   61        NaN    1
top     596-ws-training  exercise  07-04-2027 13:25:00        NaN
freq                 46        61                    1        NaN   61
mean                NaN       NaN                  NaN   5.540984  NaN
std                 NaN       NaN                  NaN   1.784879  NaN
min                 NaN       NaN                  NaN   3.000000  NaN
25%                 NaN       NaN                  NaN   5.000000  NaN
50%                 NaN       NaN                  NaN   6.000000  NaN
75%                 NaN       NaN                  NaN   6.000000  NaN
max                 NaN       NaN                  NaN  10.000000  NaN

          duration  competitive
count    61.000000          0.0
unique         NaN          NaN
top            NaN          NaN
freq           NaN          NaN
mean     93.721311          NaN
std      59.706262          NaN
min       0.000000          NaN
25%      51.000000          NaN
50%      70.000000          NaN
75%     138.000000          NaN
max     301.000000          NaN
============================================================
finger_stick
============================================================
                Patient       Section                   ts        value
count              1691          1691                 1691  1691.000000
unique                6             1                 1691          NaN
top     540-ws-training  finger_stick  07-04-2027 11:56:14          NaN
freq                577          1691                    1          NaN
mean                NaN           NaN                  NaN   147.443525
std                 NaN           NaN                  NaN    77.855789
min                 NaN           NaN                  NaN     0.000000
25%                 NaN           NaN                  NaN    99.000000
50%                 NaN           NaN                  NaN   143.000000
75%                 NaN           NaN                  NaN   195.000000
max                 NaN           NaN                  NaN   462.000000
============================================================
glucose_level
============================================================
                Patient        Section                   ts         value
count             65535          65535                65535  65535.000000
unique                6              1                64091           NaN
top     584-ws-training  glucose_level  21-05-2027 17:15:00           NaN
freq              12150          65535                    2           NaN
mean                NaN            NaN                  NaN    157.700282
std                 NaN            NaN                  NaN     60.882019
min                 NaN            NaN                  NaN     40.000000
25%                 NaN            NaN                  NaN    112.000000
50%                 NaN            NaN                  NaN    149.000000
75%                 NaN            NaN                  NaN    193.000000
max                 NaN            NaN                  NaN    400.000000
============================================================
hypo_event
============================================================
                Patient     Section                   ts
count                45          45                   45
unique                3           1                   45
top     596-ws-training  hypo_event  07-04-2027 12:17:00
freq                 28          45                    1
============================================================
illness
============================================================
                Patient  Section             ts_begin  ts_end  type  \
count                 3        3                    3     0.0   0.0
unique                3        1                    3     NaN   NaN
top     596-ws-training  illness  12-05-2027 03:25:00     NaN   NaN
freq                  1        3                    1     NaN   NaN
mean                NaN      NaN                  NaN     NaN   NaN
std                 NaN      NaN                  NaN     NaN   NaN
min                 NaN      NaN                  NaN     NaN   NaN
25%                 NaN      NaN                  NaN     NaN   NaN
50%                 NaN      NaN                  NaN     NaN   NaN
75%                 NaN      NaN                  NaN     NaN   NaN
max                 NaN      NaN                  NaN     NaN   NaN

       description
count            3
unique           1
top
freq             3
mean           NaN
std            NaN
min            NaN
25%            NaN
50%            NaN
75%            NaN
max            NaN
============================================================
meal
============================================================
                Patient Section                   ts       type       carbs
count               702     702                  702        702  702.000000
unique                6       1                  702          5         NaN
top     596-ws-training    meal  07-04-2027 12:08:00  Breakfast         NaN
freq                265     702                    1        180         NaN
mean                NaN     NaN                  NaN        NaN   47.833333
std                 NaN     NaN                  NaN        NaN   31.580739
min                 NaN     NaN                  NaN        NaN    1.000000
25%                 NaN     NaN                  NaN        NaN   24.000000
50%                 NaN     NaN                  NaN        NaN   41.000000
75%                 NaN     NaN                  NaN        NaN   60.750000
max                 NaN     NaN                  NaN        NaN  162.000000
============================================================
sleep
============================================================
                Patient Section             ts_begin               ts_end  \
count               150     150                  150                  150
unique                5       1                  150                  150
top     544-ws-training   sleep  08-04-2027 07:10:00  07-04-2027 22:54:00
freq                 43     150                    1                    1
mean                NaN     NaN                  NaN                  NaN
std                 NaN     NaN                  NaN                  NaN
min                 NaN     NaN                  NaN                  NaN
25%                 NaN     NaN                  NaN                  NaN
50%                 NaN     NaN                  NaN                  NaN
75%                 NaN     NaN                  NaN                  NaN
max                 NaN     NaN                  NaN                  NaN

           quality
count   150.000000
unique         NaN
top            NaN
freq           NaN
mean      2.460000
std       0.661806
min       1.000000
25%       2.000000
50%       3.000000
75%       3.000000
max       3.000000
============================================================
stressors
============================================================
                Patient    Section                   ts type description
count                 2          2                    2    2           2
unique                2          1                    2    1           1
top     596-ws-training  stressors  13-04-2027 15:14:00
freq                  1          2                    1    2           2
============================================================
temp_basal
============================================================
                Patient     Section             ts_begin               ts_end  \
count               355         355                  355                  355
unique                6           1                  355                  355
top     540-ws-training  temp_basal  01-05-2027 08:22:50  01-05-2027 10:52:50
freq                232         355                    1                    1
mean                NaN         NaN                  NaN                  NaN
std                 NaN         NaN                  NaN                  NaN
min                 NaN         NaN                  NaN                  NaN
25%                 NaN         NaN                  NaN                  NaN
50%                 NaN         NaN                  NaN                  NaN
75%                 NaN         NaN                  NaN                  NaN
max                 NaN         NaN                  NaN                  NaN

             value
count   355.000000
unique         NaN
top            NaN
freq           NaN
mean      0.463437
std       0.701212
min       0.000000
25%       0.000000
50%       0.000000
75%       0.800000
max       2.340000
============================================================
work
============================================================
                Patient Section             ts_begin               ts_end  \
count                52      52                   52                   52
unique                3       1                   52                   52
top     544-ws-training    work  23-04-2025 06:15:00  23-04-2025 16:00:00
freq                 30      52                    1                    1
mean                NaN     NaN                  NaN                  NaN
std                 NaN     NaN                  NaN                  NaN
min                 NaN     NaN                  NaN                  NaN
25%                 NaN     NaN                  NaN                  NaN
50%                 NaN     NaN                  NaN                  NaN
75%                 NaN     NaN                  NaN                  NaN
max                 NaN     NaN                  NaN                  NaN

        intensity
count   52.000000
unique        NaN
top           NaN
freq          NaN
mean     3.673077
std      1.216249
min      1.000000
25%      3.000000
50%      3.000000
75%      5.000000
max      6.000000

In [15]:
for name, df in dfs.items():
    if 'ts' in df.columns:
        df['ts'] = pd.to_datetime(
            df['ts'],
            format = 'mixed',
            dayfirst = True,
            errors = 'coerce'
        )

    if 'ts_begin' in df.columns:
        df['ts_begin'] = pd.to_datetime(
            df['ts_begin'],
            format = 'mixed',
            dayfirst = True,
            errors = 'coerce'
        )

    if 'ts_end' in df.columns:
        df['ts_end'] = pd.to_datetime(
            df['ts_end'],
            format = 'mixed',
            dayfirst = True,
            errors = 'coerce'
        )
    
    if 'tbegin' in df.columns:
        df['tbegin'] = pd.to_datetime(
            df['tbegin'],
            format = 'mixed',
            dayfirst = True,
            errors = 'coerce'
        )
    
    if 'tend' in df.columns:
        df['tend'] = pd.to_datetime(
            df['tend'],
            format = 'mixed',
            dayfirst = True,
            errors = 'coerce'
        )
print("All timestamps converted successfully!")

All timestamps converted successfully!

In [16]:
for name, df in dfs.items():

    print(f"\n{name}")

    for col in ["ts", "ts_begin", "ts_end", "tbegin", "tend"]:
        if col in df.columns:
            print(f"{col}: {df[col].isna().sum()} invalid values")

acceleration
ts: 0 invalid values

basal
ts: 0 invalid values

basis_gsr
ts: 0 invalid values

basis_skin_temperature
ts: 0 invalid values

basis_sleep
tbegin: 0 invalid values
tend: 0 invalid values

bolus
ts_begin: 0 invalid values
ts_end: 0 invalid values

exercise
ts: 0 invalid values

finger_stick
ts: 0 invalid values

glucose_level
ts: 0 invalid values

hypo_event
ts: 0 invalid values

illness
ts_begin: 0 invalid values
ts_end: 3 invalid values

meal
ts: 0 invalid values

sleep
ts_begin: 0 invalid values
ts_end: 0 invalid values

stressors
ts: 0 invalid values

temp_basal
ts_begin: 0 invalid values
ts_end: 0 invalid values

work
ts_begin: 0 invalid values
ts_end: 0 invalid values

In [19]:
for name, df in dfs.items():
    print(f'\n{name}')

    if 'ts' in df.columns:
        print('Start:', df['ts'].min())
        print('End:', df['ts'].max())

    elif 'ts_begin' in df.columns:
        print('Start:', df['ts_begin'].min())
        print('End:', df['ts_end'].max())

    elif 'tbegin' in df.columns:
        print('Start:', df['tbegin'].min())
        print('End:', df['tend'].max())
    
    print("Total Records:", len(df))

acceleration
Start: 2025-04-17 20:01:00
End: 2027-07-03 21:20:00
Total Records: 228027

basal
Start: 2025-04-16 00:00:00
End: 2027-06-22 14:00:00
Total Records: 357

basis_gsr
Start: 2025-04-17 20:01:00
End: 2027-07-03 21:20:00
Total Records: 228025

basis_skin_temperature
Start: 2025-04-17 20:01:00
End: 2027-07-03 21:20:00
Total Records: 228021

basis_sleep
Start: 2025-04-17 23:22:00
End: 2027-06-24 06:04:00
Total Records: 199

bolus
Start: 2025-04-16 06:48:48
End: 2027-07-03 23:18:47
Total Records: 1568

exercise
Start: 2025-04-17 18:30:00
End: 2027-07-03 09:45:00
Total Records: 61

finger_stick
Start: 2025-04-16 11:05:34
End: 2027-07-03 23:31:44
Total Records: 1691

glucose_level
Start: 2025-04-16 11:17:05
End: 2027-07-03 23:56:44
Total Records: 65535

hypo_event
Start: 2025-04-19 08:35:00
End: 2027-06-23 18:30:00
Total Records: 45

illness
Start: 2025-04-16 20:11:00
End: NaT
Total Records: 3

meal
Start: 2025-04-16 18:00:00
End: 2027-07-03 19:30:00
Total Records: 702

sleep
Start: 2025-04-17 05:36:00
End: 2027-06-22 21:30:00
Total Records: 150

stressors
Start: 2027-04-13 15:14:00
End: 2027-05-18 14:14:00
Total Records: 2

temp_basal
Start: 2025-04-22 21:03:00
End: 2027-07-04 00:00:00
Total Records: 355

work
Start: 2025-04-23 06:15:00
End: 2027-06-23 15:10:00
Total Records: 52

In [21]:
dfs["illness"]

           Patient  Section            ts_begin ts_end  type description
0  596-ws-training  illness 2027-05-12 03:25:00    NaT   NaN
1  567-ws-training  illness 2027-01-18 12:26:00    NaT   NaN
2  552-ws-training  illness 2025-04-16 20:11:00    NaT   NaN

In [20]:
for name, df in dfs.items():
    print(f"\n{name}")
    print("Unique Patients:", df["Patient"].nunique())
    print(df["Patient"].unique())

acceleration
Unique Patients: 6
['596-ws-training' '567-ws-training' '552-ws-training' '544-ws-training'
 '584-ws-training' '540-ws-training']

basal
Unique Patients: 6
['596-ws-training' '567-ws-training' '552-ws-training' '544-ws-training'
 '584-ws-training' '540-ws-training']

basis_gsr
Unique Patients: 6
['596-ws-training' '567-ws-training' '552-ws-training' '544-ws-training'
 '584-ws-training' '540-ws-training']

basis_skin_temperature
Unique Patients: 6
['596-ws-training' '567-ws-training' '552-ws-training' '544-ws-training'
 '584-ws-training' '540-ws-training']

basis_sleep
Unique Patients: 6
['596-ws-training' '567-ws-training' '552-ws-training' '544-ws-training'
 '584-ws-training' '540-ws-training']

bolus
Unique Patients: 6
['596-ws-training' '567-ws-training' '552-ws-training' '544-ws-training'
 '584-ws-training' '540-ws-training']

exercise
Unique Patients: 4
['596-ws-training' '552-ws-training' '544-ws-training' '584-ws-training']

finger_stick
Unique Patients: 6
['596-ws-training' '567-ws-training' '552-ws-training' '544-ws-training'
 '584-ws-training' '540-ws-training']

glucose_level
Unique Patients: 6
['596-ws-training' '567-ws-training' '552-ws-training' '544-ws-training'
 '584-ws-training' '540-ws-training']

hypo_event
Unique Patients: 3
['596-ws-training' '552-ws-training' '544-ws-training']

illness
Unique Patients: 3
['596-ws-training' '567-ws-training' '552-ws-training']

meal
Unique Patients: 6
['596-ws-training' '567-ws-training' '552-ws-training' '544-ws-training'
 '584-ws-training' '540-ws-training']

sleep
Unique Patients: 5
['596-ws-training' '567-ws-training' '552-ws-training' '544-ws-training'
 '584-ws-training']

stressors
Unique Patients: 2
['596-ws-training' '544-ws-training']

temp_basal
Unique Patients: 6
['596-ws-training' '567-ws-training' '552-ws-training' '544-ws-training'
 '584-ws-training' '540-ws-training']

work
Unique Patients: 3
['552-ws-training' '544-ws-training' '584-ws-training']

In [23]:
for name, df in dfs.items():
    before = len(df)

    df.drop_duplicates(inplace=True)

    after = len(df)

    print(f"{name}: Removed {before-after} duplicate rows")

acceleration: Removed 0 duplicate rows
basal: Removed 0 duplicate rows
basis_gsr: Removed 0 duplicate rows
basis_skin_temperature: Removed 0 duplicate rows
basis_sleep: Removed 0 duplicate rows
bolus: Removed 0 duplicate rows
exercise: Removed 0 duplicate rows
finger_stick: Removed 0 duplicate rows
glucose_level: Removed 0 duplicate rows
hypo_event: Removed 0 duplicate rows
illness: Removed 0 duplicate rows
meal: Removed 0 duplicate rows
sleep: Removed 0 duplicate rows
stressors: Removed 0 duplicate rows
temp_basal: Removed 0 duplicate rows
work: Removed 0 duplicate rows

In [24]:
for name, df in dfs.items():

    if "ts" in df.columns:
        df.sort_values("ts", inplace=True)

    elif "ts_begin" in df.columns:
        df.sort_values("ts_begin", inplace=True)

    elif "tbegin" in df.columns:
        df.sort_values("tbegin", inplace=True)

In [25]:
for df in dfs.values():
    df.reset_index(drop=True, inplace=True)

In [26]:
for name, df in dfs.items():

    print(name)

    print(df.info())

    print()

acceleration
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 228027 entries, 0 to 228026
Data columns (total 4 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   Patient  228027 non-null  object
 1   Section  228027 non-null  object
 2   ts       228027 non-null  datetime64[ns]
 3   value    228027 non-null  float64
dtypes: datetime64[ns](1), float64(1), object(2)
memory usage: 7.0+ MB
None

basal
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 357 entries, 0 to 356
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Patient  357 non-null    object
 1   Section  357 non-null    object
 2   ts       357 non-null    datetime64[ns]
 3   value    357 non-null    float64
dtypes: datetime64[ns](1), float64(1), object(2)
memory usage: 11.3+ KB
None

basis_gsr
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 228025 entries, 0 to 228024
Data columns (total 4 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   Patient  228025 non-null  object
 1   Section  228025 non-null  object
 2   ts       228025 non-null  datetime64[ns]
 3   value    228025 non-null  float64
dtypes: datetime64[ns](1), float64(1), object(2)
memory usage: 7.0+ MB
None

basis_skin_temperature
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 228021 entries, 0 to 228020
Data columns (total 4 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   Patient  228021 non-null  object
 1   Section  228021 non-null  object
 2   ts       228021 non-null  datetime64[ns]
 3   value    228021 non-null  float64
dtypes: datetime64[ns](1), float64(1), object(2)
memory usage: 7.0+ MB
None

basis_sleep
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199 entries, 0 to 198
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Patient  199 non-null    object
 1   Section  199 non-null    object
 2   tbegin   199 non-null    datetime64[ns]
 3   tend     199 non-null    datetime64[ns]
 4   quality  199 non-null    int64
 5   type     199 non-null    object
dtypes: datetime64[ns](2), int64(1), object(3)
memory usage: 9.5+ KB
None

bolus
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1568 entries, 0 to 1567
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Patient   1568 non-null   object
 1   Section   1568 non-null   object
 2   ts_begin  1568 non-null   datetime64[ns]
 3   ts_end    1568 non-null   datetime64[ns]
 4   type      1568 non-null   object
 5   dose      1568 non-null   float64
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 73.6+ KB
None

exercise
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Patient      61 non-null     object
 1   Section      61 non-null     object
 2   ts           61 non-null     datetime64[ns]
 3   intensity    61 non-null     int64
 4   type         61 non-null     object
 5   duration     61 non-null     int64
 6   competitive  0 non-null      float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 3.5+ KB
None

finger_stick
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1691 entries, 0 to 1690
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Patient  1691 non-null   object
 1   Section  1691 non-null   object
 2   ts       1691 non-null   datetime64[ns]
 3   value    1691 non-null   int64
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 53.0+ KB
None

glucose_level
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65535 entries, 0 to 65534
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Patient  65535 non-null  object
 1   Section  65535 non-null  object
 2   ts       65535 non-null  datetime64[ns]
 3   value    65535 non-null  int64
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 2.0+ MB
None

hypo_event
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Patient  45 non-null     object
 1   Section  45 non-null     object
 2   ts       45 non-null     datetime64[ns]
dtypes: datetime64[ns](1), object(2)
memory usage: 1.2+ KB
None

illness
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Patient      3 non-null      object
 1   Section      3 non-null      object
 2   ts_begin     3 non-null      datetime64[ns]
 3   ts_end       0 non-null      datetime64[ns]
 4   type         0 non-null      float64
 5   description  3 non-null      object
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 276.0+ bytes
None

meal
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 702 entries, 0 to 701
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Patient  702 non-null    object
 1   Section  702 non-null    object
 2   ts       702 non-null    datetime64[ns]
 3   type     702 non-null    object
 4   carbs    702 non-null    int64
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 27.6+ KB
None

sleep
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Patient   150 non-null    object
 1   Section   150 non-null    object
 2   ts_begin  150 non-null    datetime64[ns]
 3   ts_end    150 non-null    datetime64[ns]
 4   quality   150 non-null    int64
dtypes: datetime64[ns](2), int64(1), object(2)
memory usage: 6.0+ KB
None

stressors
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Patient      2 non-null      object
 1   Section      2 non-null      object
 2   ts           2 non-null      datetime64[ns]
 3   type         2 non-null      object
 4   description  2 non-null      object
dtypes: datetime64[ns](1), object(4)
memory usage: 212.0+ bytes
None

temp_basal
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 355 entries, 0 to 354
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Patient   355 non-null    object
 1   Section   355 non-null    object
 2   ts_begin  355 non-null    datetime64[ns]
 3   ts_end    355 non-null    datetime64[ns]
 4   value     355 non-null    float64
dtypes: datetime64[ns](2), float64(1), object(2)
memory usage: 14.0+ KB
None

work
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Patient    52 non-null     object
 1   Section    52 non-null     object
 2   ts_begin   52 non-null     datetime64[ns]
 3   ts_end     52 non-null     datetime64[ns]
 4   intensity  52 non-null     int64
dtypes: datetime64[ns](2), int64(1), object(2)
memory usage: 2.2+ KB
None

In [28]:
import os

processed_folder = "../data/processed"
os.makedirs(processed_folder, exist_ok=True)

for name, df in dfs.items():
    df.to_csv(f"{processed_folder}/{name}.csv", index=False)

print("All cleaned files saved!")

All cleaned files saved!